// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase app on Android.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.android,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '*****************************',
    appId: '***************************',
    messagingSenderId: '**************************',
    projectId: '**********************',
    databaseURL: '****************************',
    storageBucket: '(****)',
  );

  /// Firebase options for the Android platform.
}
